name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yaml
          activate-environment: envs
          auto-activate-base: false
      
      - name: Run tests with coverage
        run: |
          pytest --cov=BlackScholes --cov=US_YieldCurve --cov=streamlit_app --cov-report=term-missing \
                --cov-branch \
                --cov-report=term-missing \
                --cov-report=xml \

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional if repo is public
          fail_ci_if_error: true