name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yaml
          activate-environment: envs
          python-version: 3.11
          auto-activate-base: false

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=BlackScholes \
                 --cov=US_YieldCurve \
                 --cov-branch \
                 --cov-report=term-missing \
                 --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true